### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by DirtyDave30**

### CODE REVIEW

**Comment by Sir-Will** [comment]
> ark_DifficultyOffset=1

1 is default btw

**Comment by DirtyDave30** [comment]
ahh is it? maybe a 2 or 2.5 then? can i edit the commits? or need to submit another one?

**Comment by Sir-Will** [comment]
> The default Difficulty Value if the Difficulty Offset is not set is 1.0.
> http://ark.gamepedia.com/Difficulty

Edit it in your fork on the patch-1 branch.

We had 3 before which is max.

**Comment by DirtyDave30** [comment]
sorry I'm such a noob when it comes to this kind of thing, tho i do thank you for taking the time with me to explain it all.

**Pull request merged**
